name: CTFGame

options:
  bundleIdPrefix: com.matt
  deploymentTarget:
    iOS: "17.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    PRODUCT_NAME: CTFGame
    PRODUCT_BUNDLE_IDENTIFIER: com.matt.ctfgame
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: CTFGame/Info.plist
    CODE_SIGN_STYLE: Automatic
    ENABLE_PREVIEWS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    DEVELOPMENT_ASSET_PATHS: "\"CTFGame/Preview Content\""

targets:
  CTFGame:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    
    sources:
      - path: CTFGame
        excludes:
          - "*.md"
          - "*.txt"
        createIntermediateGroups: true
    
    info:
      path: CTFGame/Info.plist
    
    settings:
      base:
        INFOPLIST_FILE: CTFGame/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.matt.ctfgame
        PRODUCT_NAME: CTFGame
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        DEVELOPMENT_ASSET_PATHS: "\"CTFGame/Preview Content\""
        ENABLE_PREVIEWS: YES
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
    
    scheme:
      testTargets: []
      gatherCoverageData: false
    
    dependencies: []

schemes:
  CTFGame:
    build:
      targets:
        CTFGame: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
